name: Release Binaries

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build release binary
        run: cargo build --release --target ${{ matrix.target }} -p mcp_multi_tool

      - name: Package artifact
        if: runner.os != 'Windows'
        run: |
          mkdir -p dist
          cp target/${{ matrix.target }}/release/mcp-multi-tool dist/mcp-multi-tool-${{ matrix.target }}
      - name: Package artifact (Windows)
        if: runner.os == 'Windows'
        run: |
          New-Item -ItemType Directory -Path dist | Out-Null
          Copy-Item target\${{ matrix.target }}\release\mcp-multi-tool.exe dist\mcp-multi-tool-${{ matrix.target }}.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mcp-multi-tool-${{ matrix.target }}
          path: dist/*

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Generate checksums
        run: |
          cd dist
          find . -type f -exec shasum -a 256 {} \; > checksums.txt

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
